<a href="https://colab.research.google.com/github/VikiTarasova/DTA_2026/blob/main/Homework/21_05_26_numpy_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🏠 Домашнє завдання — NumPy

**До тьюторіалу:** Pandas + Matplotlib: Аналіз даних з нуля

---
### Правила виконання
- Кожне завдання виконуй в окремій клітинці
- Не використовуй цикли там де можна обійтись операціями NumPy
- Після виконання — запусти клітинку і перевір що результат виглядає правильно
- Якщо застряг — поверніться до відповідного розділу тьюторіалу

**Оцінювання:** кожне завдання — 1 бал. Фінальний проєкт — 3 бали. Всього: **14 балів**

---

## Розділ 1 — Масиви ndarray та атрибути

> **Що повторюємо:** `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`,
> атрибути `.shape`, `.ndim`, `.size`, `.dtype`

### ✏️ Завдання 1.1

У тебе є дані середньомісячних температур у Харкові за рік (°C):

```
-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3
```

1. Створи NumPy масив із цих значень і назви його `temps`
2. Виведи масив
3. Виведи: кількість вимірів (`ndim`), форму (`shape`), кількість елементів (`size`), тип даних (`dtype`)
4. Виведи мінімальну, максимальну температуру та середньорічну (округли до 1 знаку)

In [3]:
import numpy as np

# Твій код:

temps = np.array([-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3])

print("Масив:", temps)

print("ndim:", temps.ndim)
print("shape:", temps.shape)
print("size:", temps.size)
print("dtype:", temps.dtype)

print("Мін:", temps.min())
print("Макс:", temps.max())
print("Середня:", round(temps.mean(), 1))

Масив: [-5 -4  2 10 17 21 23 22 16  9  2 -3]
ndim: 1
shape: (12,)
size: 12
dtype: int64
Мін: -5
Макс: 23
Середня: 9.2


### ✏️ Завдання 1.2

Створи таблицю планових продажів для 3 менеджерів на 4 квартали.

1. Створи матрицю `plan` розміром **3×4**, заповнену значенням `50` (тис. грн) — використай `np.full()`
2. Виведи матрицю
3. Виведи її форму та загальну кількість елементів
4. Створи другу матрицю `bonus` розміром **3×4** із нулів — менеджери ще не отримали бонусів
5. Виведи суму `plan + bonus` і переконайся що вона рівна `plan`

In [5]:
# Твій код:
import numpy as np

plan = np.full((3, 4), 50)
print("План:\n", plan)

print("shape:", plan.shape)
print("size:", plan.size)

bonus = np.zeros((3, 4))
print("\nБонуси:\n", bonus)

total = plan + bonus
print("\nПлан + Бонуси:\n", total)
print("Рівна plan:", np.array_equal(total, plan))

План:
 [[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]]
shape: (3, 4)
size: 12

Бонуси:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

План + Бонуси:
 [[50. 50. 50. 50.]
 [50. 50. 50. 50.]
 [50. 50. 50. 50.]]
Рівна plan: True


---
## Розділ 2 — Індексація та зрізи

> **Що повторюємо:** індексація 1D і 2D масивів, зрізи `[start:stop:step]`,
> вибір рядків та стовпців матриці

### ✏️ Завдання 2.1

Є масив денних продажів магазину за 2 тижні (14 днів):

```python
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])
```

Виконай такі вибірки **без циклів**, лише через зрізи:
1. Продажі першого тижня (дні 1–7)
2. Продажі другого тижня (дні 8–14)
3. Продажі у вихідні: 6-й, 7-й, 13-й, 14-й день — використай індексацію списком `[[5,6,12,13]]`
4. Продажі через день, починаючи з першого (непарні дні: 1, 3, 5...)
5. Масив у зворотному порядку

In [6]:
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])

# Твій код:
import numpy as np

print("1 тиждень:", sales[:7])
print("2 тиждень:", sales[7:])
print("Вихідні:", sales[[5, 6, 12, 13]])
print("Непарні дні:", sales[::2])
print("Зворотній порядок:", sales[::-1])

1 тиждень: [320 415 290 480 350 620 580]
2 тиждень: [310 440 305 510 370 650 595]
Вихідні: [620 580 650 595]
Непарні дні: [320 290 350 580 440 510 650]
Зворотній порядок: [595 650 370 510 305 440 310 580 620 350 480 290 415 320]


### ✏️ Завдання 2.2

Є матриця оцінок студентів: **4 студенти × 5 предметів**.

```python
grades = np.array([
    [85, 72, 91, 78, 88],   # Олена
    [63, 88, 74, 95, 70],   # Максим
    [90, 65, 82, 70, 94],   # Аня
    [75, 80, 68, 85, 79],   # Богдан
])
```

1. Виведи всі оцінки Олени (перший рядок)
2. Виведи оцінки всіх студентів з 3-го предмету (третій стовпець)
3. Виведи підматрицю: оцінки Максима та Ані з предметів 2–4 (рядки 1–2, стовпці 1–3)
4. Виведи оцінки останнього студента з останнього предмету

In [7]:
grades = np.array([
    [85, 72, 91, 78, 88],
    [63, 88, 74, 95, 70],
    [90, 65, 82, 70, 94],
    [75, 80, 68, 85, 79],
])

# Твій код:
import numpy as np

print("Оцінки Олени:", grades[0])
print("3-й предмет:", grades[:, 2])
print("Максим та Аня, предмети 2-4:\n", grades[1:3, 1:4])
print("Останній студент, останній предмет:", grades[-1, -1])

Оцінки Олени: [85 72 91 78 88]
3-й предмет: [91 74 82 68]
Максим та Аня, предмети 2-4:
 [[88 74 95]
 [65 82 70]]
Останній студент, останній предмет: 79


---
## Розділ 3 — Математичні операції та векторизація

> **Що повторюємо:** арифметика з масивами, `np.sqrt()`, `np.round()`,
> агрегатні функції `.sum()`, `.mean()`, `.std()`, `.min()`, `.max()`, `np.median()`

### ✏️ Завдання 3.1

Є масив цін товарів у доларах. Виконай **без циклів**:

```python
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])
```

1. Переведи ціни в гривні (курс: **1 USD = 41.5 UAH**), результат округли до 2 знаків
2. Нарахуй ПДВ 20% — помнож гривневі ціни на 1.2, округли до 2 знаків
3. Знайди: мінімальну, максимальну, середню ціну з ПДВ
4. Знайди суму всіх товарів з ПДВ — це загальна вартість кошика
5. Виведи результати з поясненнями

In [8]:
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])

# Твій код:

prices_uah = np.round(prices_usd * 41.5, 2)
prices_vat = np.round(prices_uah * 1.2, 2)

print("Ціни в грн:", prices_uah)
print("Ціни з ПДВ:", prices_vat)
print("Мін:", prices_vat.min())
print("Макс:", prices_vat.max())
print("Середня:", round(prices_vat.mean(), 2))
print("Загальна вартість кошика:", prices_vat.sum())

Ціни в грн: [ 663.58 1763.75  332.   5187.5  1400.62 2788.8   414.58]
Ціни з ПДВ: [ 796.3  2116.5   398.4  6225.   1680.74 3346.56  497.5 ]
Мін: 398.4
Макс: 6225.0
Середня: 2151.57
Загальна вартість кошика: 15061.0


### ✏️ Завдання 3.2

Є дані про кількість товарів на складі та їх собівартість.
Виконай **без циклів**:

```python
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']
```

1. Порахуй загальну вартість кожного товару на складі (`quantity * cost_each`)
2. Знайди загальну вартість всього складу
3. Знайди товар з найбільшою сумарною вартістю — використай `np.argmax()`
4. Знайди товар з найменшою сумарною вартістю — `np.argmin()`
5. Виведи середню вартість одного найменування на складі

In [9]:
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']

# Твій код:

total_each = quantity * cost_each
print("Вартість кожного товару:", total_each)

total_warehouse = total_each.sum()
print("Загальна вартість складу:", total_warehouse)

max_idx = np.argmax(total_each)
print("Найбільша вартість:", names[max_idx], "-", total_each[max_idx])

min_idx = np.argmin(total_each)
print("Найменша вартість:", names[min_idx], "-", total_each[min_idx])

print("Середня вартість найменування:", round(total_each.mean(), 2))

Вартість кожного товару: [ 30000  81000  13500 171000  28500  24000  45000]
Загальна вартість складу: 393000
Найбільша вартість: Монітор - 171000
Найменша вартість: Зошит - 13500
Середня вартість найменування: 56142.86


---
## Розділ 4 — Булеве маскування і фільтрація

> **Що повторюємо:** булеві маски, фільтрація `arr[mask]`,
> `np.where()`, `.sum()` для підрахунку True

### ✏️ Завдання 4.1

Є масив часу виконання замовлень у хвилинах (норма — до 30 хв):

```python
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])
```

1. Знайди всі замовлення, виконані **вчасно** (≤ 30 хв)
2. Знайди всі **запізнілі** замовлення (> 30 хв)
3. Порахуй кількість вчасних і запізнілих
4. Знайди відсоток запізнілих замовлень (округли до 1 знаку)
5. Яка середня затримка серед запізнілих замовлень?

In [10]:
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])

# Твій код:

on_time = delivery_time[delivery_time <= 30]
late    = delivery_time[delivery_time > 30]

print("Вчасні:", on_time)
print("Запізнілі:", late)

print("Кількість вчасних:", len(on_time))
print("Кількість запізнілих:", len(late))

late_pct = round(len(late) / len(delivery_time) * 100, 1)
print("Відсоток запізнілих:", late_pct, "%")

avg_delay = round(late.mean(), 1)
print("Середня затримка серед запізнілих:", avg_delay, "хв")

Вчасні: [22 28 19 27 24 26 18 29 23 20]
Запізнілі: [35 41 55 33 48 31 52 38 44 36]
Кількість вчасних: 10
Кількість запізнілих: 10
Відсоток запізнілих: 50.0 %
Середня затримка серед запізнілих: 41.3 хв


### ✏️ Завдання 4.2

Є масив щоденних продажів за місяць. Використай `np.where()`:

```python
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)
```

1. Знайди дні з продажами **вище середнього** за місяць
2. Порахуй скільки таких днів
3. За допомогою `np.where()` створи масив `status`:
   - `'Гарний день'` — якщо продажі вище середнього
   - `'Звичайний день'` — якщо нижче або рівно
4. Виведи перші 10 днів: продажі та їх статус поряд

In [11]:
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)

# Твій код:

avg = daily.mean()
print("Середні продажі:", round(avg, 1))

above_avg = daily[daily > avg]
print("Днів вище середнього:", len(above_avg))

status = np.where(daily > avg, 'Гарний день', 'Звичайний день')

print("\nПерші 10 днів:")
for i, (sale, s) in enumerate(zip(daily[:10], status[:10]), start=1):
    print(f"День {i:2}: {sale} грн — {s}")

Середні продажі: 434.2
Днів вище середнього: 14

Перші 10 днів:
День  1: 202 грн — Звичайний день
День  2: 535 грн — Гарний день
День  3: 370 грн — Звичайний день
День  4: 206 грн — Звичайний день
День  5: 171 грн — Звичайний день
День  6: 800 грн — Гарний день
День  7: 120 грн — Звичайний день
День  8: 714 грн — Гарний день
День  9: 221 грн — Звичайний день
День 10: 566 грн — Гарний день


---
## Розділ 5 — reshape та сортування

> **Що повторюємо:** `.reshape()`, `.flatten()`, `np.sort()`, `np.argsort()`

### ✏️ Завдання 5.1

Є 1D масив з 24 показників продажів (по годинах за добу):

```python
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])
```

1. Перетвори масив у матрицю **6×4** (6 блоків по 4 години) і виведи
2. Знайди суму продажів у кожному 4-годинному блоці (по рядках)
3. Відсортуй вихідний 1D масив за **зростанням** і виведи
4. Знайди **індекси** годин відсортованих за зростанням продажів — `np.argsort()`
5. Виведи топ-3 найпродуктивніших години (їхні номери, рахуючи з 0)

In [12]:
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])

# Твій код:

matrix = hourly.reshape(6, 4)
print("Матриця 6×4:\n", matrix)

block_sums = matrix.sum(axis=1)
print("Сума по блоках:", block_sums)

sorted_arr = np.sort(hourly)
print("Відсортований масив:", sorted_arr)

sorted_idx = np.argsort(hourly)
print("Індекси за зростанням:", sorted_idx)

top3 = sorted_idx[-3:][::-1]
print("Топ-3 години:", top3)

Матриця 6×4:
 [[12  8  5  3]
 [ 4  9 18 35]
 [52 61 58 64]
 [70 67 55 48]
 [53 62 74 68]
 [45 30 22 15]]
Сума по блоках: [ 28  66 235 240 257 112]
Відсортований масив: [ 3  4  5  8  9 12 15 18 22 30 35 45 48 52 53 55 58 61 62 64 67 68 70 74]
Індекси за зростанням: [ 3  4  2  1  5  0 23  6 22 21  7 20 15  8 16 14 10  9 17 11 13 19 12 18]
Топ-3 години: [18 12 19]


---
## Розділ 6 — Генерація випадкових чисел

> **Що повторюємо:** `np.random.seed()`, `np.random.randint()`,
> `np.random.normal()`, `np.random.choice()`

### ✏️ Завдання 6.1

Змоделюй результати маркетингового опитування 50 клієнтів.

1. Встанови `np.random.seed(99)`
2. Згенеруй масив `ages` — вік 50 клієнтів: цілі числа від 18 до 65
3. Згенеруй масив `scores` — оцінки задоволеності (нормальний розподіл, середнє=7, σ=1.5), округли до 1 знаку
4. Обріж `scores` так щоб значення були від 1 до 10 — `np.clip(arr, 1, 10)`
5. Виведи:
   - середній вік клієнтів
   - середню оцінку задоволеності
   - кількість клієнтів з оцінкою >= 8 («задоволені»)
   - відсоток задоволених

In [18]:
# Твій код:

np.random.seed(99)

ages   = np.random.randint(18, 66, size=50)
scores = np.round(np.random.normal(7, 1.5, size=50), 1)
scores = np.clip(scores, 1, 10)

satisfied = scores[scores >= 8]

print("Середній вік:", round(ages.mean(), 1))
print("Середня оцінка:", round(scores.mean(), 1))
print("Задоволених клієнтів:", len(satisfied))
print("Відсоток задоволених:", round(len(satisfied) / len(scores) * 100, 1), "%")

Середній вік: 41.8
Середня оцінка: 6.9
Задоволених клієнтів: 10
Відсоток задоволених: 20.0 %


---
## 🏆 Фінальний проєкт — Аналіз даних магазину

> **Використовуємо все з тьюторіалу разом**

Ти аналітик даних невеликого магазину електроніки.
Тобі передали масив продажів за 8 тижнів (56 днів).

Виконай повний аналіз та дай відповіді на запитання керівника.

In [14]:
# Дані — не змінюй цю клітинку
np.random.seed(2024)
base = np.random.randint(200, 800, 56)

# Вихідні продаються краще
weekend_boost = np.array([1 if i % 7 in [5, 6] else 0 for i in range(56)])
sales_56 = (base + weekend_boost * np.random.randint(100, 300, 56)).astype(int)

print('Дані отримано. Масив sales_56 готовий до аналізу.')
print(f'Елементів: {sales_56.size}, форма: {sales_56.shape}')


Дані отримано. Масив sales_56 готовий до аналізу.
Елементів: 56, форма: (56,)


### Запитання 1 — Загальна статистика (Розділ 1, 3)
Виведи:
- Загальна виручка за 56 днів
- Середньоденна виручка (округли до 2 знаків)
- Мінімальний та максимальний денний продаж
- Стандартне відхилення (наскільки продажі «скачуть»)

In [15]:
# Твій код:
print("Загальна виручка:", sales_56.sum(), "грн")
print("Середньоденна виручка:", round(sales_56.mean(), 2), "грн")
print("Мінімальний продаж:", sales_56.min(), "грн")
print("Максимальний продаж:", sales_56.max(), "грн")
print("Стандартне відхилення:", round(sales_56.std(), 2), "грн")

Загальна виручка: 31819 грн
Середньоденна виручка: 568.2 грн
Мінімальний продаж: 222 грн
Максимальний продаж: 1072 грн
Стандартне відхилення: 195.52 грн


### Запитання 2 — Тижневий аналіз (Розділ 5)
1. Перетвори `sales_56` у матрицю **8×7** (8 тижнів по 7 днів)
2. Знайди виручку кожного тижня (сума по рядках)
3. Знайди найкращий тиждень і виведи його номер (рахуючи з 1) та суму
4. Знайди середньоденну виручку по кожному дню тижня (середнє по стовпцях)
5. Виведи який день тижня в середньому найприбутковіший (0=Пн, 6=Нд)

In [16]:
# Твій код:
matrix = sales_56.reshape(8, 7)

weekly = matrix.sum(axis=1)
print("Виручка по тижнях:", weekly)

best_week = np.argmax(weekly)
print(f"Найкращий тиждень: {best_week + 1}, виручка: {weekly[best_week]} грн")

daily_avg = matrix.mean(axis=0)
days = ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Нд']
print("\nСередня виручка по днях тижня:")
for day, avg in zip(days, daily_avg):
    print(f"  {day}: {round(avg, 1)} грн")

best_day = np.argmax(daily_avg)
print(f"\nНайприбутковіший день: {days[best_day]} (індекс {best_day})")

Виручка по тижнях: [4555 3921 3563 3546 5036 3300 4228 3670]
Найкращий тиждень: 5, виручка: 5036 грн

Середня виручка по днях тижня:
  Пн: 520.4 грн
  Вт: 455.5 грн
  Ср: 565.9 грн
  Чт: 607.8 грн
  Пт: 463.8 грн
  Сб: 629.8 грн
  Нд: 734.4 грн

Найприбутковіший день: Нд (індекс 6)


### Запитання 3 — Фільтрація та маскування (Розділ 4)
1. Знайди кількість **«слабких» днів** — продажі нижче 400 грн
2. Знайди кількість **«сильних» днів** — продажі вище 700 грн
3. Яка середня виручка у слабкі дні і яка у сильні?
4. Створи масив `labels` за допомогою `np.where()`:
   - `'Слабкий'` якщо < 400
   - `'Сильний'` якщо > 700
   - `'Нормальний'` в решті випадків (підказка: вкладений `np.where`)
5. Виведи перші 14 днів: продажі та їх мітки

In [17]:
# Твій код:
weak_days  = sales[sales < 400]
strong_days = sales[sales > 700]

print("Слабких днів:", len(weak_days))
print("Сильних днів:", len(strong_days))

print("Середня виручка у слабкі дні:", round(weak_days.mean(), 2))
print("Середня виручка у сильні дні:", round(strong_days.mean(), 2))

labels = np.where(sales < 400, 'Слабкий',
         np.where(sales > 700, 'Сильний', 'Нормальний'))

for day, (sale, label) in enumerate(zip(sales[:14], labels[:14]), start=1):
    print(f"День {day:2}: {sale} грн — {label}")

Слабких днів: 6
Сильних днів: 0
Середня виручка у слабкі дні: 324.17
Середня виручка у сильні дні: nan
День  1: 320 грн — Слабкий
День  2: 415 грн — Нормальний
День  3: 290 грн — Слабкий
День  4: 480 грн — Нормальний
День  5: 350 грн — Слабкий
День  6: 620 грн — Нормальний
День  7: 580 грн — Нормальний
День  8: 310 грн — Слабкий
День  9: 440 грн — Нормальний
День 10: 305 грн — Слабкий
День 11: 510 грн — Нормальний
День 12: 370 грн — Слабкий
День 13: 650 грн — Нормальний
День 14: 595 грн — Нормальний


/tmp/ipykernel_11095/864663625.py:9: RuntimeWarning: Mean of empty slice.
  print("Середня виручка у сильні дні:", round(strong_days.mean(), 2))
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


---
## ✅ Підсумок

| Розділ | Завдання | Балів | Виконано |
|--------|----------|-------|----------|
| 1 — Масиви ndarray | 1.1, 1.2 | 2 | ☐ |
| 2 — Індексація та зрізи | 2.1, 2.2 | 2 | ☐ |
| 3 — Математичні операції | 3.1, 3.2 | 2 | ☐ |
| 4 — Булеве маскування | 4.1, 4.2 | 2 | ☐ |
| 5 — reshape та сортування | 5.1 | 1 | ☐ |
| 6 — Генерація випадкових | 6.1 | 1 | ☐ |
| 🏆 Фінальний проєкт | Питання 1–3 | 3 | ☐ |
| **Разом** | | **13** | |
