<a href="https://colab.research.google.com/github/VikiTarasova/DTA_2026/blob/main/classmade/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐍 NumPy для початківців-аналітиків даних

**NumPy** (Numerical Python) — це основна бібліотека для роботи з числовими даними в Python. Вона дозволяє:
- Зберігати великі масиви чисел ефективно
- Виконувати математичні операції швидко (у 10–100 разів швидше за звичайні списки)
- Готувати дані для аналізу в pandas, matplotlib, scikit-learn

---
**Як користуватись цим блокнотом:**
- 📖 Читай теорію у текстових клітинках
- ▶️ Запускай клітинки з кодом (Shift+Enter)
- ✏️ Виконуй завдання — їх позначено як **🎯 Завдання**
- Підказки у клітинках після завдання — розкривай лише якщо застряг

---

## Розділ 0 — Встановлення та імпорт

NumPy зазвичай вже є в Anaconda / Google Colab. Якщо ні — встанови:

In [1]:
# Розкоментуй і виконай, якщо NumPy ще не встановлено:
# !pip install numpy

import numpy as np

print("NumPy версія:", np.__version__)
print("Імпорт успішний! ✅")

NumPy версія: 2.0.2
Імпорт успішний! ✅


---
## Розділ 1 — Масиви NumPy (ndarray)

### Що таке масив?

Масив NumPy (`ndarray`) — це як список Python, але:
- всі елементи **одного типу** (лише числа, або лише рядки)
- займає **менше пам'яті**
- математику можна робити **одразу з усім масивом**

```
Список Python:  [1, 2, 3, 4, 5]      ← звичайний, повільний
Масив NumPy:    array([1, 2, 3, 4, 5]) ← швидкий, для математики
```

### Створення масиву

In [ ]:
# Зі списку Python
arr1d = np.array([10, 20, 30, 40, 50])
print("1D масив:", arr1d)
print("Тип:", type(arr1d))
print("Тип елементів:", arr1d.dtype)

In [ ]:
# 2D масив (матриця) — список зі списків
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("2D масив:")
print(arr2d)
print("\nФорма (рядки, стовпці):", arr2d.shape)
print("Кількість вимірів:", arr2d.ndim)
print("Загальна кількість елементів:", arr2d.size)

In [ ]:
# Корисні функції для створення масивів

zeros = np.zeros((3, 4))          # масив нулів розміром 3×4
ones = np.ones((2, 5))            # масив одиниць розміром 2×5
rng = np.arange(0, 20, 2)         # числа від 0 до 19 з кроком 2
linspace = np.linspace(0, 1, 5)   # 5 рівномірно розподілених чисел від 0 до 1

print("Нулі 3×4:\n", zeros)
print("\nОдиниці 2×5:\n", ones)
print("\nДіапазон з кроком 2:", rng)
print("\nРівномірний поділ:", linspace)

### 🎯 Завдання 1.1

Створи масив із оцінок студента: `[85, 92, 78, 95, 88]`.
Виведи масив, його форму та тип елементів.

In [ ]:
# Твій код тут:



In [ ]:
# 💡 Підказка (запусти, щоб побачити):
hint = """
grades = np.array([85, 92, 78, 95, 88])
print(grades)
print(grades.shape)
print(grades.dtype)
"""
print(hint)

### 🎯 Завдання 1.2

Створи двовимірний масив розміром **4×3**, заповнений одиницями.
Потім виведи: скільки всього елементів у масиві?

In [ ]:
# Твій код тут:



In [ ]:
# 💡 Підказка:
hint = """
m = np.ones((4, 3))
print(m)
print("Кількість елементів:", m.size)  # 12
"""
print(hint)

---
## Розділ 2 — Індексація та зрізи

### Як отримати елементи масиву?

Індексація схожа на списки Python, але для 2D масивів використовується `[рядок, стовпець]`:

```
arr = [10, 20, 30, 40, 50]
       ↑                ↑
     [0]              [4] або [-1]
```

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print("Перший елемент:    ", arr[0])     # 10
print("Третій елемент:    ", arr[2])     # 30
print("Останній елемент:  ", arr[-1])    # 50
print("Передостанній:     ", arr[-2])    # 40

In [ ]:
# Зрізи: arr[start:stop:step]
# stop — НЕ включається!

arr = np.array([10, 20, 30, 40, 50, 60, 70])

print("arr[1:4]    =", arr[1:4])    # [20 30 40]
print("arr[:3]     =", arr[:3])     # [10 20 30] — з початку
print("arr[4:]     =", arr[4:])     # [50 60 70] — до кінця
print("arr[::2]    =", arr[::2])    # [10 30 50 70] — кожен другий
print("arr[::-1]   =", arr[::-1])   # [70 60 50 40 30 20 10] — реверс

In [ ]:
# Індексація 2D масиву
matrix = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12]
])

print("Матриця:\n", matrix)
print("\nЕлемент [0, 2] (рядок 0, стовпець 2):", matrix[0, 2])  # 3
print("Весь рядок 1:     ", matrix[1, :])   # [5 6 7 8]
print("Весь стовпець 2:  ", matrix[:, 2])   # [3 7 11]
print("Підматриця [1:, 1:3]:\n", matrix[1:, 1:3])

### 🎯 Завдання 2.1

Маємо дані продажів за тиждень: `[120, 85, 200, 95, 310, 280, 150]`
- Виведи продажі за робочі дні (пн–пт, індекси 0–4)
- Виведи продажі за вихідні (сб–нд, останні 2 елементи)
- Виведи лише непарні дні (вт, чт, сб — індекси 1, 3, 5)

In [ ]:
sales = np.array([120, 85, 200, 95, 310, 280, 150])

# Твій код тут:



In [ ]:
# 💡 Підказка:
hint = """
print("Робочі дні:", sales[:5])
print("Вихідні:   ", sales[-2:])
print("Вт, Чт, Сб:", sales[1::2])  або  sales[[1, 3, 5]]
"""
print(hint)

### 🎯 Завдання 2.2

Маємо таблицю температур: 3 міста × 5 днів.
- Виведи всі температури першого міста (рядок 0)
- Виведи температури всіх міст у третій день (стовпець 2)
- Виведи підматрицю для міст 1–2 і днів 2–4

In [ ]:
# Температури: рядки = міста (Київ, Харків, Одеса), стовпці = дні (пн–пт)
temps = np.array([
    [18, 20, 22, 19, 21],   # Київ
    [17, 19, 23, 20, 22],   # Харків
    [22, 24, 26, 25, 23]    # Одеса
])

# Твій код тут:



In [ ]:
# 💡 Підказка:
hint = """
print(temps[0, :])      # перше місто
print(temps[:, 2])      # третій день
print(temps[1:, 2:5])   # підматриця
"""
print(hint)

---
## Розділ 3 — Математичні операції

### Векторизація — магія NumPy

У NumPy операції застосовуються **до всіх елементів одразу** — це називається **векторизація**:

```python
# Звичайний Python — треба цикл:
result = [x * 2 for x in [1, 2, 3, 4, 5]]

# NumPy — без циклу, і набагато швидше:
result = np.array([1, 2, 3, 4, 5]) * 2
```

In [ ]:
prices = np.array([100, 250, 80, 320, 150])  # ціни в гривнях

# Арифметика зі скаляром (одним числом)
print("Ціни:", prices)
print("З ПДВ (×1.2):", prices * 1.2)
print("Знижка 20%:  ", prices * 0.8)
print("+ 50 грн:    ", prices + 50)

In [ ]:
# Операції між двома масивами — поелементно
qty = np.array([3, 1, 5, 2, 4])     # кількість проданих товарів

revenue = prices * qty               # виручка по кожному товару
print("Ціни:        ", prices)
print("Кількість:   ", qty)
print("Виручка:     ", revenue)
print("Разом:       ", revenue.sum())

In [ ]:
# Математичні функції NumPy
data = np.array([4, 9, 16, 25, 36, 49])

print("Квадратний корінь:", np.sqrt(data))
print("Логарифм (ln):    ", np.log(data).round(2))
print("Піднесення до ^2: ", np.power(data, 2))
print("Абсолютне значення:", np.abs(np.array([-3, 5, -1, 8])))

In [ ]:
# Агрегатні функції — підсумовують весь масив
scores = np.array([72, 88, 65, 91, 78, 84, 69, 95])

print("Оцінки:", scores)
print("Сума:      ", scores.sum())
print("Середнє:   ", scores.mean().round(2))
print("Мін:       ", scores.min())
print("Макс:      ", scores.max())
print("Стд відхил:", scores.std().round(2))
print("Медіана:   ", np.median(scores))

In [ ]:
# Агрегація по осях для 2D масиву
sales_matrix = np.array([
    [100, 150, 200],   # Магазин 1: пн, вт, ср
    [80,  120, 180],   # Магазин 2
    [200, 90,  160],   # Магазин 3
])

print("Матриця продажів:\n", sales_matrix)
print("\nСума по рядках (по кожному магазину):", sales_matrix.sum(axis=1))
print("Сума по стовпцях (по кожному дню):   ", sales_matrix.sum(axis=0))
print("Середнє по магазинах:", sales_matrix.mean(axis=1).round(1))

### 🎯 Завдання 3.1

Є дані зарплат 6 працівників у доларах: `[1200, 1500, 900, 2100, 1800, 1350]`

1. Конвертуй зарплати в гривні (курс: 1 USD = 41 UAH)
2. Порахуй середню, мінімальну та максимальну зарплату в гривнях
3. Визнач, на скільки кожна зарплата відрізняється від середньої

In [ ]:
salaries_usd = np.array([1200, 1500, 900, 2100, 1800, 1350])

# Твій код тут:



In [ ]:
# 💡 Підказка:
hint = """
salaries_uah = salaries_usd * 41
print("В гривнях:", salaries_uah)

print("Середня: ", salaries_uah.mean())
print("Мінімум: ", salaries_uah.min())
print("Максимум:", salaries_uah.max())

diff = salaries_uah - salaries_uah.mean()
print("Відхилення від середньої:", diff.round())
"""
print(hint)

### 🎯 Завдання 3.2

Маємо таблицю продажів 4 менеджерів за 3 місяці (рядки = менеджери, стовпці = місяці):

1. Знайди загальний обсяг продажів кожного менеджера
2. Знайди кращий місяць (максимум по стовпцях)
3. Знайди найкращого менеджера (підказка: `np.argmax()`)

In [ ]:
managers_sales = np.array([
    [45000, 52000, 48000],  # Менеджер 1
    [38000, 61000, 55000],  # Менеджер 2
    [72000, 68000, 70000],  # Менеджер 3
    [41000, 44000, 39000],  # Менеджер 4
])

# Твій код тут:



In [ ]:
# 💡 Підказка:
hint = """
total = managers_sales.sum(axis=1)
print("Підсумки менеджерів:", total)

best_month = managers_sales.max(axis=0)
print("Кращий місяць:      ", best_month)

best_manager = np.argmax(total)   # повертає індекс
print(f"Кращий менеджер: #{best_manager + 1} з сумою {total[best_manager]}")
"""
print(hint)

---
## Розділ 4 — Булева індексація та фільтрація

### Як фільтрувати дані?

Це одна з найважливіших технік для аналізу даних!
Замість циклів `for` з умовами `if` — одне просте вираження:

In [4]:
ages = np.array([23, 45, 18, 67, 31, 29, 52, 19, 38, 41])

# Булева маска — масив True/False
mask = ages > 30
print("Маска (вік > 30):", mask)

# Застосування маски — лишає лише True елементи
seniors = ages[mask]
print("Люди старше 30:  ", seniors)

# Коротко — в один рядок:
print("Молодші 25:      ", ages[ages < 25])

Маска (вік > 30): [False  True False  True  True False  True False  True  True]
Люди старше 30:   [45 67 31 52 38 41]
Молодші 25:       [23 18 19]


In [5]:
# Складні умови: & (і), | (або), ~ (не)
# ВАЖЛИВО: кожна умова в дужках!

# Люди від 25 до 45 років
middle = ages[(ages >= 25) & (ages <= 45)]
print("Від 25 до 45:", middle)

# Молодші 20 або старші 60
extremes = ages[(ages < 20) | (ages > 60)]
print("< 20 або > 60:", extremes)

Від 25 до 45: [45 31 29 38 41]
< 20 або > 60: [18 67 19]


In [6]:
# np.where — умовне присвоєння (як IF в Excel)
scores = np.array([72, 88, 55, 91, 48, 78, 63, 95])

# np.where(умова, значення_якщо_True, значення_якщо_False)
grades = np.where(scores >= 75, "✅ здав", "❌ не здав")
print("Оцінки: ", scores)
print("Статус:  ", grades)

Оцінки:  [72 88 55 91 48 78 63 95]
Статус:   ['❌ не здав' '✅ здав' '❌ не здав' '✅ здав' '❌ не здав' '✅ здав'
 '❌ не здав' '✅ здав']


In [7]:
# Корисні функції для пошуку
temps = np.array([22, 35, 18, 41, 29, 37, 15, 44])

print("Індекс мінімуму:", np.argmin(temps), "— значення:", temps[np.argmin(temps)])
print("Індекс максимуму:", np.argmax(temps), "— значення:", temps[np.argmax(temps)])
print("Дні > 35°C:", np.sum(temps > 35), "дні")
print("Відсоток жарких:", (np.sum(temps > 35) / len(temps) * 100), "%")

Індекс мінімуму: 6 — значення: 15
Індекс максимуму: 7 — значення: 44
Дні > 35°C: 3 дні
Відсоток жарких: 37.5 %


### 🎯 Завдання 4.1

Є дані про ціни акцій за 10 днів. Знайди:
1. Дні, коли ціна була вища за середню
2. Скільки днів ціна падала (менше 100)?
3. Позначте кожен день: "зростання" або "падіння" відносно 100

In [13]:
stock_prices = np.array([95, 102, 98, 115, 88, 121, 94, 108, 87, 119])

# Твій код тут:
print("Mean:", stock_prices.mean())
print(f'Дні, коли ціна була вища за середню: {stock_prices[stock_prices > stock_prices.mean()]}')
print(f'Скільки днів ціна падала (менше 100)? - {np.sum(stock_prices < 100)}')
print(f'Позначте кожен день: "зростання" або "падіння" відносно 100: \n{np.where(stock_prices >= 100, "зростання", "падіння")}')

Mean: 102.7
Дні, коли ціна була вища за середню: [115 121 108 119]
Скільки днів ціна падала (менше 100)? - 5
Позначте кожен день: "зростання" або "падіння" відносно 100: 
['падіння' 'зростання' 'падіння' 'зростання' 'падіння' 'зростання'
 'падіння' 'зростання' 'падіння' 'зростання']


In [ ]:
# 💡 Підказка:
hint = """
avg = stock_prices.mean()
print("Ціни вище середньої:", stock_prices[stock_prices > avg])

print("Днів < 100:", np.sum(stock_prices < 100))

trend = np.where(stock_prices >= 100, "зростання", "падіння")
print("Тренд:", trend)
"""
print(hint)

### 🎯 Завдання 4.2 — Комплексне

Є дані клієнтів інтернет-магазину: вік і сума замовлення.

1. Знайди середнє замовлення клієнтів до 30 років
2. Знайди кількість клієнтів від 30 до 50 з замовленням > 500
3. Визнач VIP-клієнтів (замовлення > 1000) і виведи їхній вік

In [19]:
client_age    = np.array([24, 45, 31, 19, 52, 28, 36, 41, 27, 58, 33, 22])
order_amount  = np.array([350, 820, 450, 120, 1200, 680, 950, 310, 780, 1500, 420, 290])

# Твій код тут:
print(f'Знайди середнє замовлення клієнтів до 30 років: {order_amount[client_age < 30].mean()}')
print(f'Знайди кількість клієнтів від 30 до 50 з замовленням > 500: {np.sum((client_age >= 30) & (client_age < 50) & (order_amount > 500))}')
client_age[order_amount > 1000]
print(f'Визнач VIP-клієнтів (замовлення > 1000) і виведи їхній вік: {client_age[order_amount > 1000]}')

Знайди середнє замовлення клієнтів до 30 років: 444.0
Знайди кількість клієнтів від 30 до 50 з замовленням > 500: 2
Визнач VIP-клієнтів (замовлення > 1000) і виведи їхній вік: [52 58]


In [ ]:
# 💡 Підказка:
hint = """
young_orders = order_amount[client_age < 30]
print("Середнє замовлення до 30р:", young_orders.mean())

mask_mid = (client_age >= 30) & (client_age <= 50) & (order_amount > 500)
print("30-50 з > 500 грн:", np.sum(mask_mid))

vip_ages = client_age[order_amount > 1000]
print("VIP клієнти, вік:", vip_ages)
"""
print(hint)

---
## Розділ 5 — Зміна форми та сортування

### reshape — зміна форми масиву

In [20]:
# Починаємо з 1D масиву з 12 елементів
flat = np.arange(1, 13)
print("Одновимірний:", flat)

# Перетворюємо в матриці — кількість елементів має збігатись!
matrix_3x4 = flat.reshape(3, 4)   # 3 рядки × 4 стовпці = 12
matrix_4x3 = flat.reshape(4, 3)   # 4 рядки × 3 стовпці = 12
matrix_2x6 = flat.reshape(2, 6)   # 2 рядки × 6 стовпців = 12

print("\n3×4:\n", matrix_3x4)
print("\n4×3:\n", matrix_4x3)

Одновимірний: [ 1  2  3  4  5  6  7  8  9 10 11 12]

3×4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

4×3:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
# -1 означає "NumPy сам порахує"
arr = np.arange(24)
m = arr.reshape(4, -1)     # 4 рядки, стовпців — автоматично (6)
print("reshape(4, -1):\n", m)
print("Форма:", m.shape)

# Назад у 1D
flat_again = m.flatten()
print("\nflatten:", flat_again)

reshape(4, -1):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Форма: (4, 6)

flatten: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [22]:
# Сортування
data = np.array([64, 23, 87, 12, 45, 91, 38])

print("Оригінал:           ", data)
print("Відсортований (↑):  ", np.sort(data))
print("Відсортований (↓):  ", np.sort(data)[::-1])
print("Індекси сортування: ", np.argsort(data))  # порядок індексів

Оригінал:            [64 23 87 12 45 91 38]
Відсортований (↑):   [12 23 38 45 64 87 91]
Відсортований (↓):   [91 87 64 45 38 23 12]
Індекси сортування:  [3 1 6 4 0 2 5]


### 🎯 Завдання 5.1

Маємо 1D масив із 20 результатів тестів. Перетвори його в матрицю 4×5 (4 групи по 5 студентів),
потім виведи топ-3 результати з усієї вибірки та середнє по кожній групі.

In [24]:
test_results = np.array([72, 88, 55, 91, 48, 78, 63, 95, 69, 82,
                         74, 51, 87, 66, 93, 58, 79, 84, 61, 77])

# Твій код тут:
print(test_results.reshape(4,5))

print(f"TOP3: {np.sort(test_results)[-3:][::-1]}\n")

print(f"середнє по кожній групі: {m.mean(axis=1).round(1)}")


[[72 88 55 91 48]
 [78 63 95 69 82]
 [74 51 87 66 93]
 [58 79 84 61 77]]
TOP3: [95 93 91]

середнє по кожній групі: [ 2.5  8.5 14.5 20.5]


In [ ]:
# 💡 Підказка:
hint = """
groups = test_results.reshape(4, 5)
print("Матриця 4×5:\n", groups)

top3 = np.sort(test_results)[-3:]  # або [::-1][:3]
print("Топ-3:", top3)

group_avg = groups.mean(axis=1).round(1)
print("Середнє по групах:", group_avg)
"""
print(hint)

---
## Розділ 6 — Генерація випадкових чисел

Випадкові числа потрібні для: симуляцій, тестових даних, машинного навчання

In [25]:
# Налаштування seed — для відтворюваних результатів
rng = np.random.default_rng(seed=42)   # сучасний спосіб

# Рівномірний розподіл — від 0 до 1
uniform = rng.random(5)
print("Рівномірний [0,1):", uniform.round(3))

# Цілі числа в діапазоні
integers = rng.integers(1, 101, size=10)   # від 1 до 100, 10 штук
print("Цілі від 1 до 100:", integers)

# Нормальний розподіл (середнє=0, σ=1)
normal = rng.normal(loc=170, scale=10, size=8)   # зріст людей: μ=170, σ=10
print("Нормальний (зріст):", normal.round(1))

Рівномірний [0,1): [0.774 0.439 0.859 0.697 0.094]
Цілі від 1 до 100: [53 98 74 77 72 79 52 13 84 46]
Нормальний (зріст): [178.8 177.8 170.7 181.3 174.7 161.4 173.7 160.4]


In [26]:
# Перемішування та вибірка
items = np.array(["яблуко", "банан", "груша", "персик", "слива", "манго"])

# Перемішати
shuffled = rng.permutation(items)
print("Перемішано:", shuffled)

# Вибрати 3 випадкових без повторень
sample = rng.choice(items, size=3, replace=False)
print("Вибірка 3:", sample)

Перемішано: ['персик' 'груша' 'банан' 'манго' 'слива' 'яблуко']
Вибірка 3: ['банан' 'груша' 'яблуко']


### 🎯 Завдання 6.1

Симулюй кидання кубика 1000 разів. Порахуй:
1. Скільки разів випало кожне число від 1 до 6 (підказка: `np.bincount`)
2. Яка частота випадання шістки (у відсотках)?
3. Середнє значення за 1000 кидань (теоретично має бути 3.5)

In [33]:
rng = np.random.default_rng(seed=0)

# Твій код тут:
# rng.integers(1, 7, size=1000)

rolls = rng.integers(1, 7, size=1000)

# Скільки разів випало кожне число від 1 до 6 (підказка: np.bincount)
n_count = np.bincount(rolls)[1:]

# Яка частота випадання шістки (у відсотках)?
n_count[5] / len(rolls) * 100

# Середнє значення за 1000 кидань (теоретично має бути 3.5)
rolls.mean()

np.float64(3.6)

In [ ]:
# 💡 Підказка:
hint = """
rolls = rng.integers(1, 7, size=1000)

counts = np.bincount(rolls)[1:]  # [1:] щоб прибрати нульовий індекс
print("Кількість кожного:", counts)

print("Частота шістки: ", round(np.sum(rolls == 6) / 1000 * 100, 1), "%")
print("Середнє:        ", rolls.mean().round(3))
"""
print(hint)

---
## 🏆 Фінальний проєкт — Аналіз даних магазину

Використай все вивчене! Маємо дані інтернет-магазину за місяць.

In [34]:
# Дані магазину
np.random.seed(42)

n = 30  # кількість днів
days = np.arange(1, n + 1)

# Відвідувачі, замовлення, середній чек
visitors     = np.random.randint(200, 800, size=n)
orders       = (visitors * np.random.uniform(0.05, 0.15, size=n)).astype(int)
avg_check    = np.random.uniform(300, 900, size=n).round(2)
daily_revenue = (orders * avg_check).round(2)

print("=== Дані за місяць ===")
print(f"{'День':>4} {'Відвідувачі':>12} {'Замовлення':>11} {'Сер. чек':>9} {'Виручка':>10}")
print("-" * 52)
for i in range(10):  # перші 10 днів
    print(f"{days[i]:>4} {visitors[i]:>12} {orders[i]:>11} {avg_check[i]:>9.0f} {daily_revenue[i]:>10.0f}")
print("... (ще 20 рядків) ...")

=== Дані за місяць ===
День  Відвідувачі  Замовлення  Сер. чек    Виручка
----------------------------------------------------
   1          302          27       805      21745
   2          635          34       570      19375
   3          470          69       537      37059
   4          306          22       856      18832
   5          271          16       736      11782
   6          220          24       496      11902
   7          321          28       642      17984
   8          666          98       612      60025
   9          414          40       877      35068
  10          530          72       807      58084
... (ще 20 рядків) ...


### 🎯 Фінальне завдання

Виконай повний аналіз даних магазину:

**1. Загальна статистика:**
- Загальна виручка за місяць
- Середня денна виручка
- Найкращий і найгірший день

**2. Конверсія:**
- Порахуй конверсію по кожному дню: `orders / visitors * 100`
- Яка середня конверсія?
- Скільки днів конверсія перевищувала 10%?

**3. Сегментація:**
- Знайди «сильні» дні (виручка > середньої)
- Знайди «слабкі» дні (виручка < 70% від середньої)
- Порівняй середній чек у сильні та слабкі дні

**4. Тижневий аналіз:**
- Reshape виручку у формат (4 тижні × ... днів)
- Знайди кращий тиждень за сумою виручки

In [ ]:
# Твій аналіз тут:

# 1. Загальна статистика


# 2. Конверсія


# 3. Сегментація


# 4. Тижневий аналіз


In [ ]:
# 💡 Підказка до фінального проєкту:
hint = """
# 1. Загальна статистика
print("Загальна виручка:  ", daily_revenue.sum().round())
print("Середня денна:     ", daily_revenue.mean().round())
best_day  = days[np.argmax(daily_revenue)]
worst_day = days[np.argmin(daily_revenue)]
print(f"Найкращий день: {best_day}, найгірший: {worst_day}")

# 2. Конверсія
conversion = orders / visitors * 100
print("Середня конверсія:", conversion.mean().round(2), "%")
print("Днів з конв. > 10%:", np.sum(conversion > 10))

# 3. Сегментація
avg_rev = daily_revenue.mean()
strong  = daily_revenue > avg_rev
weak    = daily_revenue < avg_rev * 0.7
print("Сер. чек у сильні дні:", avg_check[strong].mean().round())
print("Сер. чек у слабкі дні:", avg_check[weak].mean().round())

# 4. Тижні (30 днів = 4 тижні × 7 + 2 дні, беремо перші 28)
weekly = daily_revenue[:28].reshape(4, 7)
weekly_totals = weekly.sum(axis=1)
best_week = np.argmax(weekly_totals) + 1
print("Виручка по тижнях:", weekly_totals.round())
print(f"Кращий тиждень: #{best_week}")
"""
print(hint)

---
## 📋 Шпаргалка — Найважливіші функції NumPy

| Функція | Опис | Приклад |
|---|---|---|
| `np.array()` | Створити масив | `np.array([1,2,3])` |
| `np.zeros(shape)` | Масив нулів | `np.zeros((3,4))` |
| `np.ones(shape)` | Масив одиниць | `np.ones((2,5))` |
| `np.arange(start, stop, step)` | Діапазон | `np.arange(0,10,2)` |
| `np.linspace(start, stop, n)` | Рівний поділ | `np.linspace(0,1,5)` |
| `.shape` | Форма масиву | `arr.shape` → `(3,4)` |
| `.dtype` | Тип даних | `arr.dtype` → `int64` |
| `.reshape()` | Змінити форму | `arr.reshape(2,6)` |
| `.flatten()` | Розгорнути в 1D | `arr.flatten()` |
| `.sum()` / `.mean()` | Сума / Середнє | `arr.sum(axis=0)` |
| `.min()` / `.max()` | Мін / Макс | `arr.max()` |
| `.std()` | Стандартне відхилення | `arr.std()` |
| `np.sort()` | Сортування | `np.sort(arr)` |
| `np.argmin()` / `np.argmax()` | Індекс мін/макс | `np.argmax(arr)` |
| `np.where(cond, a, b)` | Умовне присвоєння | `np.where(arr>0, 1, -1)` |
| Булева маска | Фільтрація | `arr[arr > 5]` |

---

## Що далі?

- **pandas** — табличні дані, DataFrame
- **matplotlib** — візуалізація даних
- **scikit-learn** — машинне навчання (використовує NumPy під капотом)

Корисні ресурси:
- [Офіційна документація NumPy](https://numpy.org/doc/)
- [NumPy Quickstart](https://numpy.org/doc/stable/user/quickstart.html)